# Generated by Django 3.0.8 on 2020-08-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('temp', models.CharField(max_length=30)),
                ('rain', models.CharField(max_length=30)),
                ('hum', models.CharField(max_length=30)),
                ('ws', models.CharField(max_length=30)),
                ('wd', models.CharField(max_length=30)),
            ],
        ),
    ]
