# Generated by Django 3.0.8 on 2020-08-13 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='BBC',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('time', models.CharField(max_length=100)),
        #         ('temp', models.CharField(max_length=100)),
        #         ('RP', models.CharField(max_length=100)),
        #         ('weather', models.CharField(max_length=100)),
        #     ],
        # ),
        migrations.CreateModel(
            name='database_content',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'database_content',
            },
        ),
        migrations.CreateModel(
            name='database_raintest',
            fields=[
                ('date', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('temper1', models.CharField(max_length=50)),
                ('temper2', models.CharField(max_length=50)),
                ('rain', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'database_raintest',
            },
        ),
        migrations.CreateModel(
            name='database_test',
            fields=[
                ('date', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('temper1', models.CharField(max_length=50)),
                ('temper2', models.CharField(max_length=50)),
                ('rain', models.CharField(max_length=50)),
                ('wind', models.CharField(max_length=50)),
                ('raintype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'database_test',
            },
        ),
        # migrations.CreateModel(
        #     name='KOREA',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('day', models.CharField(max_length=100)),
        #         ('time', models.CharField(max_length=100)),
        #         ('weather', models.CharField(max_length=100)),
        #         ('RP', models.CharField(max_length=100)),
        #         ('rain', models.CharField(max_length=100)),
        #         ('temp', models.CharField(max_length=100)),
        #         ('hum', models.CharField(max_length=100)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='NORWAY',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('time', models.CharField(max_length=100)),
        #         ('weather', models.CharField(max_length=100)),
        #         ('temp', models.CharField(max_length=100)),
        #         ('rain', models.CharField(max_length=100)),
        #         ('wind', models.CharField(max_length=100)),
        #     ],
        # ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.User')),
            ],
        ),
    ]
