# Generated by Django 3.0.8 on 2020-08-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30)),
                ('temp', models.CharField(max_length=30)),
                ('RP', models.CharField(max_length=30)),
                ('weather', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='KOREA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('weather', models.CharField(max_length=30)),
                ('RP', models.CharField(max_length=30)),
                ('rain', models.CharField(max_length=30)),
                ('temp', models.CharField(max_length=30)),
                ('hum', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NORWAY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30)),
                ('weather', models.CharField(max_length=30)),
                ('temp', models.CharField(max_length=30)),
                ('rain', models.CharField(max_length=30)),
                ('wind', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
